### ISSUE TITLE
Cannot update a document with softDelete

### ISSUE THREAD

**Issue by cguilarte** [nour-karoui/mongoose-soft-delete#22]
I am trying to update a document, but it won't let me, now if I manage to remove the softdelete from the mongo schema it works for me, therefore I think there is a problem with the plugin. I give example:

<img width="627" alt="Captura de pantalla 2024-04-10 a la(s) 1 58 03 p  m" src="https://github.com/nour-karoui/mongoose-soft-delete/assets/4249917/b1235820-3e1b-408e-8348-1beabbbf8bbe">

<img width="624" alt="Captura de pantalla 2024-04-10 a la(s) 1 58 37 p  m" src="https://github.com/nour-karoui/mongoose-soft-delete/assets/4249917/5fd2dbeb-a369-4c1a-8776-22dc85b7aa72">

I hope you can help me.

**Comment by Willis0826** [comment]
Hi @cguilarte ,

I am willing to help in this case. I tested the `updateMany` with a unit test and it works.

You can find the unit test [here](https://github.com/nour-karoui/mongoose-soft-delete/pull/23/files#diff-cece62ae24396a5d51e8f2a2cb3abba900652084488023f4de9669eaaf6f81e8R84-R96).

What is `generateId()` in your code? Does it return an `ObjectId` object?

**Comment by cguilarte** [comment]
Hello @Willis0826 , thank you for responding, I will continue testing and checking that I am not placing something wrong, and yes, generateId returns an objectId, I still tried with other attributes and nothing.

**Comment by rival14** [comment]
Any update?
I'm facing same issue here

I'm using updateOne() but not updated

**Comment by cguilarte** [comment]
@rival14 still nothing, I still have the same problem, for now I have it without soft erasing. 
@Willis0826 Can you show how you have configured the document schema?

**Comment by Willis0826** [comment]
@cguilarte Yes, sure! I tested the functionality using the provided unit test code. You can find the document schema [here](https://github.com/nour-karoui/mongoose-soft-delete/pull/23/files#diff-cece62ae24396a5d51e8f2a2cb3abba900652084488023f4de9669eaaf6f81e8L4-L11).

**Comment by Willis0826** [comment]
@cguilarte @rival14 Hi, are you still experiencing this issue?

**Comment by Willis0826** [comment]
I will close this issue for now. Please feel free to reopen the issue if you are still running into this issue.
