### ISSUE TITLE
How can I add this plugin to NestJs globally?

### ISSUE THREAD

**Issue by rostamiani** [nour-karoui/mongoose-soft-delete#3]
How can I add this plugin globally?
This is the old method that does not work anymore in newer versions of mongoose:

```ts
import { Connection } from 'mongoose';
import { softDeletePlugin } from 'soft-delete-plugin-mongoose';
...
@Module({
  imports: [
    MongooseModule.forRoot(MONGO_URI, {
      connectionFactory: (connection: Connection) => {
        connection.plugin(softDeletePlugin);
        // ^--------- Error: Property 'plugin' does not exist on type 'Connection'.
        return connection;
      },
    }),
```

Thanks

**Comment by nour-karoui** [comment]
Hello, sorry for the late response, check out this link https://docs.nestjs.com/techniques/mongodb, forFeatureAsync, it allows you to add a plugin for each model, I couldn't find how to add it to the connection
