### ISSUE TITLE
idDeleted not considered in populate match

### ISSUE THREAD

**Issue by SergioArrighi** [nour-karoui/mongoose-soft-delete#9]
Hello,
I have a document with a string ref to a second document.
The second document uses soft delete.

I would like to be able to populate the first document with a match condition to populate only soft deleted sub-documents.

let as: A[] = await this.aModel.find().populate({
      path: 'bs',
      match: { isDeleted: { $eq: true } },
      model: B
    })

This condition gets completely ignore and I only have non deleted A documents in response.
Is there a way to achieve this behaviour?

Thanks and best regards

**Comment by nour-karoui** [comment]
I apologize for this very late reply, but that is the point of this package, to add isDeleted and not fetch them with the not deleted ones, anyways there a function called findDeleted to fetch the deleted documents.
